server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasksdb
    username: postgres
    password: password
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
  security:
    user:
      name: admin
      password: secret123

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  health:
    redis:
      enabled: true
    diskspace:
      enabled: true
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true