server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasksdb
    username: postgres
    password: password
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    root: INFO
