global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'distributed-task-scheduler'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']  # Or your Spring Boot host:port